[19.945383072] 2019-08-09 05:42:04,878 - INFO - launcher: Starting sanity checks
[19.945383072] 2019-08-09 05:42:04,878 - INFO - launcher: Checking for Python 3.5+
[19.945383072] 2019-08-09 05:42:04,878 - INFO - launcher: Checking console encoding
[19.945383072] 2019-08-09 05:42:04,878 - INFO - launcher: Setting console encoding to UTF-8
[20.943403244] 2019-08-09 05:42:04,879 - INFO - launcher: Ensuring we're in the right environment
[20.943403244] 2019-08-09 05:42:04,879 - INFO - launcher: Adding local bins/ folder to path
[309.172391891] 2019-08-09 05:42:05,167 - INFO - launcher: Required checks passed.
[309.172391891] 2019-08-09 05:42:05,167 - INFO - launcher: Optional checks passed.
[309.172391891] 2019-08-09 05:42:05,167 - INFO - launcher: Moving old musicbot log

######################### PRE-RUN SANITY CHECKS PASSED #########################

[0.7440679073333740] 2019-08-09 05:42:05,602 - WARNING - musicbot.config | In config.py::MainThread(13748), line 120 in run_checks: i18n file does not exist. Trying to fallback to config/i18n/en.json.
[0.7440679073333740] 2019-08-09 05:42:05,602 - INFO - musicbot.config | In config.py::MainThread(13748), line 131 in run_checks: Using i18n: config/i18n/en.json
[0.7450625896453857] 2019-08-09 05:42:05,603 - DEBUG - musicbot.bot | In bot.py::MainThread(13748), line 226 in _setup_logging: Set logging level to INFO
[0.7460358142852783] 2019-08-09 05:42:05,604 - DEBUG - musicbot.json | In json.py::MainThread(13748), line 8 in __init__: Init JSON obj with config/i18n/en.json
[0.7560329437255859] 2019-08-09 05:42:05,614 - INFO - musicbot.bot | In bot.py::MainThread(13748), line 91 in __init__: Starting MusicBot release-120519
[0.7570073604583740] 2019-08-09 05:42:05,615 - INFO - musicbot.bot | In bot.py::MainThread(13748), line 97 in __init__: Loaded autoplaylist with 2531 entries
[6.0027363300323486] 2019-08-09 05:42:10,860 - DEBUG - musicbot.bot | In bot.py::MainThread(13748), line 949 in on_ready: Connection established, ready to go.
[6.0027363300323486] 2019-08-09 05:42:10,860 - DEBUG - musicbot.bot | In bot.py::MainThread(13748), line 340 in _cache_app_info: Caching app info
[6.2191841602325439] 2019-08-09 05:42:11,077 - DEBUG - musicbot.bot | In bot.py::MainThread(13748), line 771 in _scheck_ensure_env: Ensuring data folders exist
[6.2211775779724121] 2019-08-09 05:42:11,079 - DEBUG - musicbot.bot | In bot.py::MainThread(13748), line 787 in _scheck_server_permissions: Checking server permissions
[6.2211775779724121] 2019-08-09 05:42:11,079 - DEBUG - musicbot.bot | In bot.py::MainThread(13748), line 791 in _scheck_autoplaylist: Auditing autoplaylist
[6.2211775779724121] 2019-08-09 05:42:11,079 - DEBUG - musicbot.bot | In bot.py::MainThread(13748), line 795 in _scheck_configs: Validating config
[6.2211775779724121] 2019-08-09 05:42:11,079 - DEBUG - musicbot.config | In config.py::MainThread(13748), line 228 in async_validate: Validating options...
[6.2211775779724121] 2019-08-09 05:42:11,079 - DEBUG - musicbot.bot | In bot.py::MainThread(13748), line 798 in _scheck_configs: Validating permissions config
[6.2211775779724121] 2019-08-09 05:42:11,079 - DEBUG - musicbot.permissions | In permissions.py::MainThread(13748), line 94 in async_validate: Validating permissions...
[6.2211775779724121] 2019-08-09 05:42:11,079 - INFO - musicbot.bot | In bot.py::MainThread(13748), line 966 in on_ready: Connected: 609088272660037632/Ìë∏Ïπò Î¥á#5176
[6.2211775779724121] 2019-08-09 05:42:11,079 - INFO - musicbot.bot | In bot.py::MainThread(13748), line 974 in on_ready: Owner:     549251082610671636/ÎßàÌò∏#0663

[6.2221441268920898] 2019-08-09 05:42:11,080 - INFO - musicbot.bot | In bot.py::MainThread(13748), line 977 in on_ready: Guild List:
[6.2221441268920898] 2019-08-09 05:42:11,080 - INFO - musicbot.bot | In bot.py::MainThread(13748), line 981 in on_ready:  - üè∞Ìë∏ÏπòÏôïÍµ≠üè∞
[6.2231421470642090] 2019-08-09 05:42:11,081 - INFO - musicbot.bot | In bot.py::MainThread(13748), line 1037 in on_ready: Not bound to any text channels
[6.2231421470642090] 2019-08-09 05:42:11,081 - INFO - musicbot.bot | In bot.py::MainThread(13748), line 1063 in on_ready: Not autojoining any voice channels
[12.5605492591857910] 2019-08-09 05:42:17,418 - INFO - musicbot.bot | In bot.py::MainThread(13748), line 2680 in on_message: 549251082610671636/ÎßàÌò∏#0663: +summon
[13.2250494956970215] 2019-08-09 05:42:18,083 - INFO - musicbot.bot | In bot.py::MainThread(13748), line 1926 in cmd_summon: Joining üè∞Ìë∏ÏπòÏôïÍµ≠üè∞/üìûÍ¥ëÏû•üìû
[13.2269463539123535] 2019-08-09 05:42:18,085 - DEBUG - musicbot.bot | In bot.py::MainThread(13748), line 530 in on_player_stop: Running on_player_stop
[17.8880181312561035] 2019-08-09 05:42:22,746 - INFO - musicbot.bot | In bot.py::MainThread(13748), line 2680 in on_message: 549251082610671636/ÎßàÌò∏#0663: +s
[17.8880181312561035] 2019-08-09 05:42:22,746 - ERROR - musicbot.bot | In bot.py::MainThread(13748), line 2809 in on_message: Error in skip: CommandError: Can't skip! The player is not playing!
Traceback (most recent call last):
  File "C:\Users\ÍπÄÏÉÅÍ∑ú\Desktop\Ìë∏Ïπò Î¥á\MusicBot\musicbot\bot.py", line 2787, in on_message
    response = await handler(**handler_kwargs)
  File "C:\Users\ÍπÄÏÉÅÍ∑ú\Desktop\Ìë∏Ïπò Î¥á\MusicBot\musicbot\bot.py", line 2057, in cmd_skip
    raise exceptions.CommandError(self.str.get('cmd-skip-none', "Can't skip! The player is not playing!"), expire_in=20)
musicbot.exceptions.CommandError: Can't skip! The player is not playing!
[22.6172418594360352] 2019-08-09 05:42:27,475 - INFO - musicbot.bot | In bot.py::MainThread(13748), line 2680 in on_message: 549251082610671636/ÎßàÌò∏#0663: +p Î©îÌä∏Î¶¨Ïä§
[24.8171293735504150] 2019-08-09 05:42:29,675 - DEBUG - musicbot.bot | In bot.py::MainThread(13748), line 1400 in cmd_play: {'_type': 'url', 'url': 'ytsearch:Î©îÌä∏Î¶¨Ïä§', 'ie_key': None, 'extractor': 'generic', 'webpage_url': 'Î©îÌä∏Î¶¨Ïä§', 'webpage_url_basename': 'Î©îÌä∏Î¶¨Ïä§', 'extractor_key': 'Generic'}
[28.5319371223449707] 2019-08-09 05:42:33,390 - DEBUG - musicbot.entry | In entry.py::MainThread(13748), line 56 in get_ready_future: Created future for None
[28.5329582691192627] 2019-08-09 05:42:33,391 - DEBUG - musicbot.bot | In bot.py::MainThread(13748), line 622 in on_player_entry_added: Running on_player_entry_added
[28.5329582691192627] 2019-08-09 05:42:33,391 - DEBUG - musicbot.bot | In bot.py::MainThread(13748), line 707 in serialize_queue: Serializing queue for 599642468652417024
[28.5369491577148438] 2019-08-09 05:42:33,395 - INFO - musicbot.entry | In entry.py::MainThread(13748), line 292 in _really_download: Download started: https://www.youtube.com/watch?v=seNNCbiXTSY
[29.8213837146759033] 2019-08-09 05:42:34,679 - INFO - musicbot.entry | In entry.py::MainThread(13748), line 302 in _really_download: Download complete: https://www.youtube.com/watch?v=seNNCbiXTSY
[30.5421636104583740] 2019-08-09 05:42:35,400 - DEBUG - musicbot.entry | In entry.py::MainThread(13748), line 56 in get_ready_future: Created future for audio_cache\youtube-seNNCbiXTSY-MV_10cm_Mattress_Live.webm
[30.5421636104583740] 2019-08-09 05:42:35,400 - FFMPEG - musicbot.player | In player.py::MainThread(13748), line 290 in _play: Creating player with options: -nostdin -vn audio_cache\youtube-seNNCbiXTSY-MV_10cm_Mattress_Live.webm
[30.9739811420440674] 2019-08-09 05:42:35,832 - DEBUG - musicbot.player | In player.py::MainThread(13748), line 303 in _play: Playing <musicbot.player.SourcePlaybackCounter object at 0x00000267F1891940> using <discord.voice_client.VoiceClient object at 0x00000267F1431978>
[30.9739811420440674] 2019-08-09 05:42:35,832 - DEBUG - musicbot.bot | In bot.py::MainThread(13748), line 458 in on_player_play: Running on_player_play
[30.9739811420440674] 2019-08-09 05:42:35,832 - DEBUG - musicbot.bot | In bot.py::MainThread(13748), line 707 in serialize_queue: Serializing queue for 599642468652417024
[45.6516582965850830] 2019-08-09 05:42:50,509 - INFO - musicbot.bot | In bot.py::MainThread(13748), line 2680 in on_message: 549251082610671636/ÎßàÌò∏#0663: +s
